name: predator_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Iconos
  cupertino_icons: ^1.0.8
  
  # Gestión de Estado e Inyección
  get_it: ^7.6.0
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^3.0.3
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9

  # Utilidades
  signature: ^5.5.0
  go_router: ^10.1.0 
  intl: ^0.18.1      
  uuid: ^4.5.2
  flutter_slidable: ^4.0.3
  rxdart: ^0.27.7

  # Excel export
  excel: ^4.0.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/